version: '3.3'

volumes:
  postgres_data:
  static_data:
  media_data:  
services:
  db:
    image: postgres:13.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: alexfofanov/foodgram:1.0
    restart: always
    volumes:
      - static_data:/code/foodgram/static/
      - media_data:/code/foodgram/media/
    
    # command: python manage.py migrate  
    # command: python manage.py collectstatic
    # command: python manage.py load_ingredients
    # command: python manage.py load_tags
      
    command: gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000 # --access-logfile gunicorn_access.log
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static_data:/code/foodgram/static/
      - media_data:/code/foodgram/media/
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - web
