# Generated by Django 3.1.7 on 2021-03-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20210310_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7)),
                ('slug', models.SlugField(blank=True, max_length=15, null=True, unique=True)),
                ('color', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='lunch',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='food.Tag'),
        ),
    ]
