# Generated by Django 3.1.7 on 2021-03-16 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20210312_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingridient',
            name='ingridient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingridients', to='food.ingridient'),
        ),
        migrations.AlterField(
            model_name='recipeingridient',
            name='quantity',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='recipeingridient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingridients', to='food.recipe'),
        ),
    ]
