# Generated by Django 3.1.7 on 2021-03-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20210316_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingridient',
            name='quantity',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
